baseURL = "https://andreybratukhin.github.io/"
languageCode = "en-us"
title = "Personal Blog"
description = "Personal blog about software engineering"
theme = "hugo-xmin"
googleAnalytics = "UA-28993181-7"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
pygmentsCodeFences = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Personal Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[[menu.sidebar]]
    name = "Logic Games: Puzzly Game"
    url = "http://puzzlygame.com/"

[params]
    description = ""
    footer = "&copy; 2018. All rights reserved."
