name = "XMin"
license = "MIT"
description = "Bootstrap theme based on XMin"
homepage = ""
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Andrey Bratukhin"
  homepage = "https://andreybratukhin.github.io"
